"""Proximity of D1 baseball rosters to their schools, by tier (Phase 9 spec, design/phase9_recruiting.md, Section 2).

Inputs (all committed): data/ncaa_2025/roster_aggregates/hometown_by_school.csv (hometown state counts by school, 2025 rosters,
232 teams), data/ncaa_2025/school_locations_2025.csv (IPEDS coordinates; scripts/build_school_locations.py) and
data/census/CenPop2020_Mean_ST.txt (Census 2020 state centres of population). Hometowns are state-level, so an out-of-state
player's distance is from the school to his home state's centre of population; in-state players count as within every cut.
Shares are means over schools within a tier (each school weighted equally). Writes reports/proximity_2025.md.
    python3 scripts/proximity_by_tier.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
STATE_ABBR = {"Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR", "California": "CA", "Colorado": "CO", "Connecticut": "CT",
              "Delaware": "DE", "District of Columbia": "DC", "Florida": "FL", "Georgia": "GA", "Hawaii": "HI", "Idaho": "ID", "Illinois": "IL",
              "Indiana": "IN", "Iowa": "IA", "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME", "Maryland": "MD",
              "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN", "Mississippi": "MS", "Missouri": "MO", "Montana": "MT", "Nebraska": "NE",
              "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM", "New York": "NY", "North Carolina": "NC",
              "North Dakota": "ND", "Ohio": "OH", "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI",
              "South Carolina": "SC", "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX", "Utah": "UT", "Vermont": "VT", "Virginia": "VA",
              "Washington": "WA", "West Virginia": "WV", "Wisconsin": "WI", "Wyoming": "WY", "Puerto Rico": "PR"}
CUTS = (300, 500, 1000)


def miles(a1, o1, a2, o2):
    a1, o1, a2, o2 = map(np.radians, (a1, o1, a2, o2))
    d = np.sin((a2 - a1) / 2) ** 2 + np.cos(a1) * np.cos(a2) * np.sin((o2 - o1) / 2) ** 2
    return 3958.8 * 2 * np.arcsin(np.sqrt(d))


def main() -> None:
    loc = pd.read_csv(ROOT / "data/ncaa_2025/school_locations_2025.csv")
    c = pd.read_csv(ROOT / "data/census/CenPop2020_Mean_ST.txt", encoding="utf-8-sig")
    cen = c.assign(st=c.STNAME.map(STATE_ABBR)).set_index("st")[["LATITUDE", "LONGITUDE"]]
    h = pd.read_csv(ROOT / "data/ncaa_2025/roster_aggregates/hometown_by_school.csv")
    h = h[h.tier.isin(["p4", "mid", "low"])].merge(loc[["ncaa_team_id", "state", "latitude", "longitude"]], left_on="team_ncaa_id",
                                                     right_on="ncaa_team_id")
    tot = h.groupby("team_ncaa_id")["count"].sum()
    us = h[h.area_type == "us_state"].join(cen, on="hometown_area")
    us["miles"] = miles(us.latitude, us.longitude, us.LATITUDE, us.LONGITUDE)
    ins = us.hometown_area == us.state
    res = pd.DataFrame({"tier": h.groupby("team_ncaa_id").tier.first()})
    res["in_state"] = us[ins].groupby("team_ncaa_id")["count"].sum().reindex(tot.index, fill_value=0) / tot
    for cut in CUTS:
        res[f"within_{cut}"] = us[ins | (us.miles <= cut)].groupby("team_ncaa_id")["count"].sum().reindex(tot.index, fill_value=0) / tot
    res["foreign"] = h[h.area_type != "us_state"].groupby("team_ncaa_id")["count"].sum().reindex(tot.index, fill_value=0) / tot
    oos = us[~ins]
    res["out_of_state_miles"] = oos.groupby("team_ncaa_id").apply(lambda g: np.average(g.miles, weights=g["count"]), include_groups=False)
    g = res.groupby("tier").agg(["mean", "std", "count"])
    md = ["# Proximity of D1 baseball rosters, 2025", "",
          "Generated by scripts/proximity_by_tier.py. Hometowns are state-level (roster aggregates). In-state players count as near; an "
          "out-of-state player's distance is from the school (IPEDS) to his home state's centre of population (Census 2020). Means over "
          "schools within a tier, with the SD across schools.", "",
          "| Tier | Schools | In-state | Within 300 mi | Within 500 mi | Within 1000 mi | Foreign | Mean miles, out-of-state players |",
          "|---|---|---|---|---|---|---|---|"]
    for t in ("p4", "mid", "low"):
        r = g.loc[t]
        md.append(f"| {t} | {int(r[('in_state', 'count')])} | " + " | ".join(f"{r[(k, 'mean')]:.3f} ± {r[(k, 'std')]:.3f}" for k in
                  ("in_state", "within_300", "within_500", "within_1000", "foreign")) + f" | {r[('out_of_state_miles', 'mean')]:.0f} |")
    md += ["", "In-state shares by tier differ little; P4 rosters draw their out-of-state players from further away. The SD across "
           "schools is large in every tier, so pipelines are school-specific."]
    (ROOT / "reports/proximity_2025.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
