"""Roster aggregates: coverage and handedness shares, for the Phase 3 go/no-go (owner request 2026-10-07).

Coverage by tier, conference and region (the conference's main footprint, a stand-in for the school's location,
which the data does not hold; P4 conferences span regions and are shown as their own group). Handedness: left-handed
pitchers' share by role (starter / reliever), batters' L / R / switch by position group, overall and by tier, with
95% intervals clustered by conference (players on one team, and teams in one conference, are not independent
draws: ratio estimator over conference totals) next to the plain binomial (Wilson) interval.

Reads data/ncaa_2025/roster_aggregates/ and data/ncaa_2025/pbp/teams_2025.csv; writes reports/roster_representativeness.md.
    python3 scripts/roster_representativeness.py
"""
from __future__ import annotations

import math
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
AGG = ROOT / "data/ncaa_2025/roster_aggregates"
# the conference's main footprint (census region); GUESS for conferences that straddle regions (noted)
REGION = {"America East": "Northeast", "Ivy League": "Northeast", "MAAC": "Northeast", "NEC": "Northeast", "Patriot": "Northeast",
          "CAA": "Northeast", "Atlantic 10": "Northeast", "Big East": "Northeast",
          "Horizon": "Midwest", "Summit League": "Midwest", "MAC": "Midwest", "MVC": "Midwest", "OVC": "Midwest",
          "Southland": "South", "SWAC": "South", "Big South": "South", "SoCon": "South", "ASUN": "South", "Sun Belt": "South",
          "CUSA": "South", "The American": "South",
          "Mountain West": "West", "WAC": "West", "WCC": "West", "Big West": "West",
          "ACC": "P4", "SEC": "P4", "Big Ten": "P4", "Big 12": "P4", "DI Independent": "P4"}
Z = 1.959964


def wilson(x: float, n: float) -> tuple[float, float]:
    if n <= 0:
        return float("nan"), float("nan")
    p = x / n
    d = 1 + Z * Z / n
    c = (p + Z * Z / (2 * n)) / d
    h = Z * math.sqrt(p * (1 - p) / n + Z * Z / (4 * n * n)) / d
    return c - h, c + h


def clustered(xs: list, ns: list) -> tuple[float, float, float]:
    """Ratio estimate sum x / sum n over clusters and its 95% interval (linearised variance)."""
    X, N, C = sum(xs), sum(ns), len(xs)
    p = X / N if N else float("nan")
    if C < 2 or N == 0:
        return p, float("nan"), float("nan")
    v = C / (C - 1) * sum((x - p * n) ** 2 for x, n in zip(xs, ns)) / N ** 2
    return p, p - Z * math.sqrt(v), p + Z * math.sqrt(v)


def main() -> None:
    teams = pd.read_csv(ROOT / "data/ncaa_2025/pbp/teams_2025.csv")
    listed = pd.read_csv(ROOT / "tools/roster_teams.csv")
    listed = listed[listed.d1 == 1] if "d1" in listed else listed
    t = listed.merge(teams.rename(columns={"ncaa_team_id": "team_ncaa_id"})[["team_ncaa_id", "conference", "tier"]], on="team_ncaa_id", how="left")
    fail = pd.read_csv(AGG / "failures.csv")
    parsed_ids = set(pd.read_csv(AGG / "hometown_by_school.csv").team_ncaa_id)
    t["status"] = ["parsed" if i in parsed_ids else ("failed" if i in set(fail.team_ncaa_id) else "not attempted") for i in t.team_ncaa_id]
    t["region"] = t.conference.map(REGION).fillna("other")
    md = ["# Roster aggregates: coverage and handedness", "",
          "Source: data/ncaa_2025/roster_aggregates/ (fetch rosters workflow; counts and shares only). Generated by scripts/roster_representativeness.py.", ""]
    cov = ROOT / AGG / "coverage.csv"
    c = pd.read_csv(cov)
    md += ["Fetch dates: " + ", ".join(c[c.metric.str.startswith("fetch")].value.astype(str).unique()), ""] if c.metric.str.startswith("fetch").any() else []
    md += ["## Coverage", "", "| Group | Teams | Parsed | Share | Failed | Not attempted |", "|---|---|---|---|---|---|"]
    for col, order in (("tier", ["p4", "mid", "low"]), ("region", ["P4", "Northeast", "Midwest", "South", "West"])):
        for g in order:
            s = t[t[col] == g]
            md.append(f"| {col} {g} | {len(s)} | {(s.status == 'parsed').sum()} | {(s.status == 'parsed').mean():.2f} | {(s.status == 'failed').sum()} | {(s.status == 'not attempted').sum()} |")
    s = t
    md.append(f"| all | {len(s)} | {(s.status == 'parsed').sum()} | {(s.status == 'parsed').mean():.2f} | {(s.status == 'failed').sum()} | {(s.status == 'not attempted').sum()} |")
    md += ["", "By conference (parsed / teams): " + "; ".join(
        f"{k} {(g.status == 'parsed').sum()}/{len(g)}" for k, g in t.sort_values(["tier", "conference"]).groupby("conference", sort=False)) + ".", ""]
    lk = pd.read_csv(AGG / "linkage.csv")
    md += ["Play-by-play plate appearances whose batter (pitcher) is matched to a parsed roster: " + "; ".join(
        f"{r.scope_value} {r.side} {r.share_pa_or_bf_matched:.3f}" for r in lk[lk.scope_value.isin(["all", "p4", "mid", "low"])].itertuples()) + ".", ""]
    # pitchers: LHP share by role
    pr = pd.read_csv(AGG / "pitcher_throws_by_role.csv")
    md += ["## Left-handed pitchers, share by role", "", "| Scope | Role | Pitchers | LHP share | 95% CI (clustered by conference) | 95% CI (binomial) |", "|---|---|---|---|---|---|"]
    conf = pr[pr.scope == "conference"].merge(teams[["conference", "tier"]].drop_duplicates(), left_on="scope_value", right_on="conference")
    for scope, sel in (("all", conf), ("p4", conf[conf.tier == "p4"]), ("mid", conf[conf.tier == "mid"]), ("low", conf[conf.tier == "low"])):
        for role in ("starter", "reliever"):
            g = sel[sel.role == role]
            by = g.groupby("scope_value").apply(lambda d: pd.Series({"x": d[d.throws == "L"].pitchers.sum(), "n": d[d.throws.isin(["L", "R"])].pitchers.sum()}), include_groups=False)
            p, lo, hi = clustered(list(by.x), list(by.n))
            wl, wh = wilson(by.x.sum(), by.n.sum())
            md.append(f"| {scope} | {role} | {int(by.n.sum())} | {p:.3f} | {lo:.3f}–{hi:.3f} | {wl:.3f}–{wh:.3f} |")
    # batters: L / R / S by position group
    hb = pd.read_csv(AGG / "handedness_by_position.csv")
    hc = hb[(hb.scope == "conference") & (hb.position_group != "P")].merge(teams[["conference", "tier"]].drop_duplicates(), left_on="scope_value", right_on="conference")
    md += ["", "## Batters: bats L / R / switch by position group", "", "Position players (the P group left out; two-way players kept). Shares of those with a listed bats value.", "",
           "| Scope | Position | Players | L | R | S (switch) |", "|---|---|---|---|---|---|"]
    for scope, sel in (("all", hc), ("p4", hc[hc.tier == "p4"]), ("mid", hc[hc.tier == "mid"]), ("low", hc[hc.tier == "low"])):
        for pos in ["all"] + sorted(p_ for p_ in sel.position_group.unique() if p_ != "unknown"):
            g = sel if pos == "all" else sel[sel.position_group == pos]
            cells = []
            n_tot = int(g[g.bats.isin(["L", "R", "S"])]["count"].sum())
            for b in ("L", "R", "S"):
                by = g.groupby("scope_value").apply(lambda d: pd.Series({"x": d[d.bats == b]["count"].sum(), "n": d[d.bats.isin(["L", "R", "S"])]["count"].sum()}), include_groups=False)
                p, lo, hi = clustered(list(by.x), list(by.n))
                cells.append(f"{p:.3f} ({lo:.3f}–{hi:.3f})")
            md.append(f"| {scope} | {pos} | {n_tot} | " + " | ".join(cells) + " |")
    md += ["", "Intervals: 95%, clustered by conference (ratio estimator over conference totals); the binomial interval for pitchers is shown for comparison. "
           "Region is the conference's main footprint (GUESS for straddling conferences: CAA, Atlantic 10, Big East as Northeast, OVC as Midwest), a stand-in for the school's location, which the data does not hold.", ""]
    (ROOT / "reports/roster_representativeness.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
